### ISSUE TITLE
npm库1.0.8版本安装提示 Not Found: @hzero-front-ui/c7n-ui@3.0.0-alpha.28

### ISSUE THREAD

**Issue by enjoyWeb** [open-hand/choerodon-front-master#4]
安装[npm库](https://www.npmjs.com/package/@choerodon/master/v/1.0.8)提示@hzero-front-ui/c7n-ui@3.0.0-alpha.28

```
λ npm install @choerodon/master@1.0.8 --save
npm WARN deprecated @types/classnames@2.3.1: This is a stub types definition. classnames provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/query-string@6.3.0: This is a stub types definition. query-string provides its own type definitions, so you do not need this installed.
npm WARN deprecated axios@0.16.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm ERR! code E404
npm ERR! 404 Not Found: @hzero-front-ui/c7n-ui@3.0.0-alpha.28

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dtLingZhong\AppData\Roaming\npm-cache\_logs\2022-06-16T02_32_19_557Z-debug.log
```

**Comment by enjoyWeb** [comment]
淘宝源提示这个
```
λcnpm install @choerodon/master@1.0.8 --save
× Install fail! Error: GET https://registry.npm.taobao.org/@hzero-front-ui%2Fcore resp onse 404 status
Error: GET https://registry.npm.taobao.org/@hzero-front-ui%2Fcore response 404 status
    at get (C:\Users\dtLingZhong\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\get.js:68:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getFullPackageMeta (C:\Users\dtLingZhong\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\download\npm.js:127:18)
    at async resolve (C:\Users\dtLingZhong\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\download\npm.js:47:24)
    at async module.exports (C:\Users\dtLingZhong\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\download\npm.js:22:19)
    at async module.exports (C:\Users\dtLingZhong\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\download\index.js:21:10)
    at async _install (C:\Users\dtLingZhong\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install.js:125:16)
    at async install (C:\Users\dtLingZhong\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install.js:26:12)
    at async mapper (C:\Users\dtLingZhong\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install.js:266:9)
npminstall version: 5.4.1
npminstall args: d:\Program Files\nodejs\node.exe C:\Users\dtLingZhong\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --fix-bug-versions --china --userconfig=C:\Users\dtLingZhong\.cnpmrc --disturl=https://npmmirror.com/mirrors/node --registry=https://registry.npm.taobao.org @choerodon/master@1.0.8 --save
```

**Comment by enjoyWeb** [comment]
这个开源项目是有人在维护，在管理运营麽<@_@>
